name:                trek
version:             0.1.0.0
github:              "githubuser/trek"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Jonathan Fischoff"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/trek#readme>

default-extensions:
- QuasiQuotes
- RecordWildCards
- LambdaCase
- RankNTypes
- ScopedTypeVariables
- OverloadedStrings
- GeneralizedNewtypeDeriving
- DerivingVia
- DeriveGeneric
- DeriveAnyClass
- TupleSections

dependencies:
- base >= 4.7 && < 5
- postgresql-simple
- pg-transact
- tmp-postgres
- time
- text
- postgresql-simple-opts
- resource-pool
- bytestring
- semigroups
- exceptions
- time-qq
- cryptonite
- memory
- interpolatedstring-perl6
- temporary
- async
- filepath
- split
- directory
- containers
- aeson
- process

library:
  source-dirs: src

executables:
  trek-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    dependencies:
    - trek

tests:
  test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hspec-discover
    - trek
    - tmp-postgres
    - hspec-expectations-lifted
    - hspec-expectations-monadthrow
